In [1]:
#Import dependencies
import pandas as pd
import os
import numpy as np

In [2]:
#Load CSV
file_to_load = ("SF 2020 CO.csv")
CO_2020 =pd.read_csv(file_to_load)
CO_2020.head()

,Date,Source,Site ID,POC,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2020,AQS,60010009,1,0.7,ppm,8,Oakland,18,75.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
1,01/02/2020,AQS,60010009,1,0.7,ppm,8,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
2,01/03/2020,AQS,60010009,1,0.9,ppm,10,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
3,01/04/2020,AQS,60010009,1,0.8,ppm,9,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
4,01/05/2020,AQS,60010009,1,0.7,ppm,8,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935

In [3]:
#Check Columns
CO_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Max 8-hour CO Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [4]:
#Check Null Values
CO_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [5]:
#Drop Columns
CO_2020= CO_2020.drop(columns=['Source','Site ID','POC','AQS_PARAMETER_CODE','DAILY_OBS_COUNT','PERCENT_COMPLETE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'SITE_LATITUDE', 'SITE_LONGITUDE'], axis=1)

In [6]:
#Check DataFrame
CO_2020.head()

,Date,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE,Site Name,COUNTY
0,01/01/2020,0.7,ppm,8,Oakland,Alameda
1,01/02/2020,0.7,ppm,8,Oakland,Alameda
2,01/03/2020,0.9,ppm,10,Oakland,Alameda
3,01/04/2020,0.8,ppm,9,Oakland,Alameda
4,01/05/2020,0.7,ppm,8,Oakland,Alameda

In [7]:
#Rename Site Name & Daily Concentration Columns
CO_2020 = CO_2020.rename(columns={"Site Name": "Site_Name"})
CO_2020 = CO_2020.rename(columns={"Daily Max 8-hour CO Concentration":"Daily_Max_8-hour_CO_Concentration"})
CO_2020.head()

,Date,Daily_Max_8-hour_CO_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
0,01/01/2020,0.7,ppm,8,Oakland,Alameda
1,01/02/2020,0.7,ppm,8,Oakland,Alameda
2,01/03/2020,0.9,ppm,10,Oakland,Alameda
3,01/04/2020,0.8,ppm,9,Oakland,Alameda
4,01/05/2020,0.7,ppm,8,Oakland,Alameda

In [8]:
#Filter for SF & Oakland West
CO_2020 = CO_2020[(CO_2020.Site_Name == "Oakland West") | (CO_2020.Site_Name == "San Francisco")]
CO_2020.head(10)

,Date,Daily_Max_8-hour_CO_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
366,01/01/2020,0.9,ppm,10,Oakland West,Alameda
367,01/02/2020,1.7,ppm,19,Oakland West,Alameda
368,01/03/2020,2.1,ppm,24,Oakland West,Alameda
369,01/04/2020,1.1,ppm,13,Oakland West,Alameda
370,01/05/2020,1.3,ppm,15,Oakland West,Alameda
371,01/06/2020,0.8,ppm,9,Oakland West,Alameda
372,01/07/2020,1.3,ppm,15,Oakland West,Alameda
373,01/08/2020,0.8,ppm,9,Oakland West,Alameda
374,01/09/2020,0.9,ppm,10,Oakland West,Alameda
375,01/10/2020,1.1,ppm,13,Oakland West,Alameda

In [9]:
#Check Count
CO_2020.count()

Date                                 701
Daily_Max_8-hour_CO_Concentration    701
UNITS                                701
DAILY_AQI_VALUE                      701
Site_Name                            701
COUNTY                               701
dtype: int64

In [10]:
#To CSV
CO_2020.to_csv(r'CO_2020_clean.csv', header= True, index=False)

In [11]:
##Load CSV for NO2
file_to_load = ("SF 2020 NO2.csv")
NO2_2020 =pd.read_csv(file_to_load)
NO2_2020.head()

,Date,Source,Site ID,POC,Daily Max 1-hour NO2 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2020,AQS,60010007,1,18.5,ppb,17,Livermore,23,96.0,42602,Nitrogen dioxide (NO2),41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
1,01/02/2020,AQS,60010007,1,22.7,ppb,21,Livermore,23,96.0,42602,Nitrogen dioxide (NO2),41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
2,01/03/2020,AQS,60010007,1,23.6,ppb,22,Livermore,23,96.0,42602,Nitrogen dioxide (NO2),41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
3,01/04/2020,AQS,60010007,1,21.2,ppb,20,Livermore,23,96.0,42602,Nitrogen dioxide (NO2),41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
4,01/05/2020,AQS,60010007,1,23.0,ppb,22,Livermore,23,96.0,42602,Nitrogen dioxide (NO2),41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217

In [12]:
#Check Columns
NO2_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 1-hour NO2 Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [13]:
#Check Null Values
NO2_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [14]:
#Drop Columns
NO2_2020 = NO2_2020.drop(columns=['Source','Site ID','POC','AQS_PARAMETER_CODE','DAILY_OBS_COUNT','PERCENT_COMPLETE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'SITE_LATITUDE', 'SITE_LONGITUDE'], axis=1)

In [15]:
#Check DataFrame
NO2_2020.head()

,Date,Daily Max 1-hour NO2 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,COUNTY
0,01/01/2020,18.5,ppb,17,Livermore,Alameda
1,01/02/2020,22.7,ppb,21,Livermore,Alameda
2,01/03/2020,23.6,ppb,22,Livermore,Alameda
3,01/04/2020,21.2,ppb,20,Livermore,Alameda
4,01/05/2020,23.0,ppb,22,Livermore,Alameda

In [16]:
#Rename Site Name & Daily Concentration Columns
NO2_2020 = NO2_2020.rename(columns={"Site Name": "Site_Name"})
NO2_2020 = NO2_2020.rename(columns={"Daily Max 1-hour NO2 Concentration":"Daily_Max_1-hour_NO2_Concentration"})
NO2_2020.head()

,Date,Daily_Max_1-hour_NO2_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
0,01/01/2020,18.5,ppb,17,Livermore,Alameda
1,01/02/2020,22.7,ppb,21,Livermore,Alameda
2,01/03/2020,23.6,ppb,22,Livermore,Alameda
3,01/04/2020,21.2,ppb,20,Livermore,Alameda
4,01/05/2020,23.0,ppb,22,Livermore,Alameda

In [17]:
#Filter for SF & Oakland West
NO2_2020 = NO2_2020[(NO2_2020.Site_Name == "Oakland West") | (NO2_2020.Site_Name == "San Francisco")]
NO2_2020.head(10)

,Date,Daily_Max_1-hour_NO2_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
726,01/01/2020,28.0,ppb,26,Oakland West,Alameda
727,01/02/2020,34.2,ppb,32,Oakland West,Alameda
728,01/07/2020,33.8,ppb,31,Oakland West,Alameda
729,01/08/2020,33.4,ppb,31,Oakland West,Alameda
730,01/09/2020,27.9,ppb,25,Oakland West,Alameda
731,01/10/2020,26.3,ppb,25,Oakland West,Alameda
732,01/11/2020,29.8,ppb,27,Oakland West,Alameda
733,01/12/2020,27.2,ppb,25,Oakland West,Alameda
734,01/13/2020,24.3,ppb,23,Oakland West,Alameda
735,01/14/2020,31.4,ppb,29,Oakland West,Alameda

In [18]:
#Check Count for SF & Oakland West
NO2_2020.count()

Date                                  687
Daily_Max_1-hour_NO2_Concentration    687
UNITS                                 687
DAILY_AQI_VALUE                       687
Site_Name                             687
COUNTY                                687
dtype: int64

In [19]:
# To CSV
NO2_2020.to_csv(r'NO2_2020_clean.csv', header= True, index=False)

In [20]:
##Load CSV for Ozone
file_to_load = ("SF 2020 Ozone.csv")
Ozone_2020 =pd.read_csv(file_to_load)
Ozone_2020.head()

,Date,Source,Site ID,POC,Daily Max 8-hour Ozone Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2020,AQS,60010007,1,0.025,ppm,23,Livermore,17,100.0,44201,Ozone,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
1,01/02/2020,AQS,60010007,1,0.017,ppm,16,Livermore,17,100.0,44201,Ozone,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
2,01/03/2020,AQS,60010007,1,0.013,ppm,12,Livermore,17,100.0,44201,Ozone,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
3,01/04/2020,AQS,60010007,1,0.028,ppm,26,Livermore,17,100.0,44201,Ozone,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
4,01/05/2020,AQS,60010007,1,0.031,ppm,29,Livermore,17,100.0,44201,Ozone,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217

In [21]:
#Check Columns
Ozone_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 8-hour Ozone Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [22]:
#Check Null Values
Ozone_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [23]:
#Drop Columns
Ozone_2020 = Ozone_2020.drop(columns=['Source','Site ID','POC','AQS_PARAMETER_CODE','DAILY_OBS_COUNT','PERCENT_COMPLETE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'SITE_LATITUDE', 'SITE_LONGITUDE'], axis=1)

In [24]:
#Check DataFrame
Ozone_2020.head()

,Date,Daily Max 8-hour Ozone Concentration,UNITS,DAILY_AQI_VALUE,Site Name,COUNTY
0,01/01/2020,0.025,ppm,23,Livermore,Alameda
1,01/02/2020,0.017,ppm,16,Livermore,Alameda
2,01/03/2020,0.013,ppm,12,Livermore,Alameda
3,01/04/2020,0.028,ppm,26,Livermore,Alameda
4,01/05/2020,0.031,ppm,29,Livermore,Alameda

In [25]:
#Rename Site Name & Daily Concentraion Columns
Ozone_2020 = Ozone_2020.rename(columns={"Site Name": "Site_Name"})
Ozone_2020 = Ozone_2020.rename(columns={"Daily Max 8-hour Ozone Concentration": "Daily_Max_8-hour_Ozone_Concentration"})
Ozone_2020.head()

,Date,Daily_Max_8-hour_Ozone_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
0,01/01/2020,0.025,ppm,23,Livermore,Alameda
1,01/02/2020,0.017,ppm,16,Livermore,Alameda
2,01/03/2020,0.013,ppm,12,Livermore,Alameda
3,01/04/2020,0.028,ppm,26,Livermore,Alameda
4,01/05/2020,0.031,ppm,29,Livermore,Alameda

In [26]:
#Filter for SF & Oakland West
Ozone_2020 = Ozone_2020[(Ozone_2020.Site_Name == "Oakland West") | (Ozone_2020.Site_Name == "San Francisco")]
Ozone_2020.head(10)

,Date,Daily_Max_8-hour_Ozone_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
728,01/01/2020,0.020,ppm,19,Oakland West,Alameda
729,01/02/2020,0.017,ppm,16,Oakland West,Alameda
730,01/03/2020,0.010,ppm,9,Oakland West,Alameda
731,01/04/2020,0.024,ppm,22,Oakland West,Alameda
732,01/05/2020,0.033,ppm,31,Oakland West,Alameda
733,01/06/2020,0.014,ppm,13,Oakland West,Alameda
734,01/07/2020,0.030,ppm,28,Oakland West,Alameda
735,01/08/2020,0.032,ppm,30,Oakland West,Alameda
736,01/09/2020,0.023,ppm,21,Oakland West,Alameda
737,01/10/2020,0.028,ppm,26,Oakland West,Alameda

In [27]:
#Check count for SF & Oakland West
Ozone_2020.count()

Date                                    728
Daily_Max_8-hour_Ozone_Concentration    728
UNITS                                   728
DAILY_AQI_VALUE                         728
Site_Name                               728
COUNTY                                  728
dtype: int64

In [28]:
#To CSV
Ozone_2020.to_csv(r'Ozone_2020_clean.csv', header= True, index=False)

In [29]:
##Load CSV for Pb
#file_to_load = ("SF 2020 Pb.csv")
#Pb_2020 =pd.read_csv(file_to_load)
#Pb_2020.head()

In [30]:
#Check Columns
#Pb_2020.columns

In [31]:
#Check Null Values
#Pb_2020.columns.isnull()

In [32]:
#Drop Columns
#Pb_2020 = Pb_2020.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [33]:
#Check DataFrame
#Pb_2020.head()

In [34]:
#Check count
#Pb_2020.count()

In [35]:
##Load CSV for PM2.5
file_to_load = ("SF 2020 PM2.5.csv")
PM2_5_2020 =pd.read_csv(file_to_load)
PM2_5_2020.head()

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2020,AQS,60010007,3,8.6,ug/m3 LC,36,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
1,01/02/2020,AQS,60010007,3,4.5,ug/m3 LC,19,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
2,01/03/2020,AQS,60010007,3,14.2,ug/m3 LC,55,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
3,01/04/2020,AQS,60010007,3,10.9,ug/m3 LC,45,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
4,01/05/2020,AQS,60010007,3,7.8,ug/m3 LC,33,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217

In [36]:
#Check Columns
PM2_5_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean PM2.5 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [37]:
#Check Null Values
PM2_5_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [38]:
#Drop Columns
PM2_5_2020 = PM2_5_2020.drop(columns=['Source','Site ID','POC','AQS_PARAMETER_CODE','DAILY_OBS_COUNT','PERCENT_COMPLETE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'SITE_LATITUDE', 'SITE_LONGITUDE'], axis=1)

In [39]:
#Check DataFrame
PM2_5_2020.head()

,Date,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,COUNTY
0,01/01/2020,8.6,ug/m3 LC,36,Livermore,Alameda
1,01/02/2020,4.5,ug/m3 LC,19,Livermore,Alameda
2,01/03/2020,14.2,ug/m3 LC,55,Livermore,Alameda
3,01/04/2020,10.9,ug/m3 LC,45,Livermore,Alameda
4,01/05/2020,7.8,ug/m3 LC,33,Livermore,Alameda

In [40]:
#Rename Site Name & Daily Concentration Columns
PM2_5_2020 = PM2_5_2020.rename(columns={"Site Name": "Site_Name"})
PM2_5_2020 = PM2_5_2020.rename(columns={"Daily Mean PM2.5 Concentration": "Daily_Mean_PM2.5_Concentration"})
PM2_5_2020.head()

,Date,Daily_Mean_PM2.5_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
0,01/01/2020,8.6,ug/m3 LC,36,Livermore,Alameda
1,01/02/2020,4.5,ug/m3 LC,19,Livermore,Alameda
2,01/03/2020,14.2,ug/m3 LC,55,Livermore,Alameda
3,01/04/2020,10.9,ug/m3 LC,45,Livermore,Alameda
4,01/05/2020,7.8,ug/m3 LC,33,Livermore,Alameda

In [41]:
#Filter for SF & Oakland West
PM2_5_2020 = PM2_5_2020[(PM2_5_2020.Site_Name == "Oakland West") | (PM2_5_2020.Site_Name == "San Francisco")]
PM2_5_2020.head(10)

,Date,Daily_Mean_PM2.5_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
720,01/01/2020,10.7,ug/m3 LC,45,Oakland West,Alameda
721,01/02/2020,9.4,ug/m3 LC,39,Oakland West,Alameda
722,01/03/2020,21.7,ug/m3 LC,71,Oakland West,Alameda
723,01/04/2020,7.4,ug/m3 LC,31,Oakland West,Alameda
724,01/05/2020,2.5,ug/m3 LC,10,Oakland West,Alameda
725,01/06/2020,6.1,ug/m3 LC,25,Oakland West,Alameda
726,01/07/2020,7.6,ug/m3 LC,32,Oakland West,Alameda
727,01/08/2020,3.7,ug/m3 LC,15,Oakland West,Alameda
728,01/09/2020,4.0,ug/m3 LC,17,Oakland West,Alameda
729,01/10/2020,6.2,ug/m3 LC,26,Oakland West,Alameda

In [42]:
#Check count for SF & Oakland West
PM2_5_2020.count()

Date                              720
Daily_Mean_PM2.5_Concentration    720
UNITS                             720
DAILY_AQI_VALUE                   720
Site_Name                         720
COUNTY                            720
dtype: int64

In [43]:
#To CSV
PM2_5_2020.to_csv(r'PM2_5_2020_clean.csv', header= True, index=False)

In [44]:
##Load CSV for SO2
file_to_load = ("SF 2020 SO2.csv")
SO2_2020 =pd.read_csv(file_to_load)
SO2_2020.head()

,Date,Source,Site ID,POC,Daily Max 1-hour SO2 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2020,AQS,60010011,1,0.5,ppb,0,Oakland West,22,92.0,42401,Sulfur dioxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.814781,-122.282347
1,01/02/2020,AQS,60010011,1,1.2,ppb,1,Oakland West,22,92.0,42401,Sulfur dioxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.814781,-122.282347
2,01/03/2020,AQS,60010011,1,1.8,ppb,1,Oakland West,19,79.0,42401,Sulfur dioxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.814781,-122.282347
3,01/04/2020,AQS,60010011,1,1.4,ppb,1,Oakland West,22,92.0,42401,Sulfur dioxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.814781,-122.282347
4,01/05/2020,AQS,60010011,1,0.7,ppb,0,Oakland West,22,92.0,42401,Sulfur dioxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.814781,-122.282347

In [45]:
#Check Columns
SO2_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 1-hour SO2 Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [46]:
#Check Null Values
SO2_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [47]:
#Drop Columns
SO2_2020 = SO2_2020.drop(columns=['Source','Site ID','POC','AQS_PARAMETER_CODE','DAILY_OBS_COUNT','PERCENT_COMPLETE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'SITE_LATITUDE', 'SITE_LONGITUDE'], axis=1)

In [48]:
#Check DataFrame
SO2_2020.head()

,Date,Daily Max 1-hour SO2 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,COUNTY
0,01/01/2020,0.5,ppb,0,Oakland West,Alameda
1,01/02/2020,1.2,ppb,1,Oakland West,Alameda
2,01/03/2020,1.8,ppb,1,Oakland West,Alameda
3,01/04/2020,1.4,ppb,1,Oakland West,Alameda
4,01/05/2020,0.7,ppb,0,Oakland West,Alameda

In [52]:
#Rename Site Name Column
SO2_2020 = SO2_2020.rename(columns={"Site Name": "Site_Name"})
SO2_2020.head()

,Date,Daily Max 1-hour SO2 Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
0,01/01/2020,0.5,ppb,0,Oakland West,Alameda
1,01/02/2020,1.2,ppb,1,Oakland West,Alameda
2,01/03/2020,1.8,ppb,1,Oakland West,Alameda
3,01/04/2020,1.4,ppb,1,Oakland West,Alameda
4,01/05/2020,0.7,ppb,0,Oakland West,Alameda

In [49]:
#Rename Site Name & Daily Concentration Columns
SO2_2020 = SO2_2020.rename(columns={"Site Name": "Site_Name"})
SO2_2020 = SO2_2020.rename(columns={"Daily Max 1-hour SO2 Concentration": "Daily_Max_1-hour_SO2_Concentration"})
SO2_2020.head()

,Date,Daily_Max_1-hour_SO2_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
0,01/01/2020,0.5,ppb,0,Oakland West,Alameda
1,01/02/2020,1.2,ppb,1,Oakland West,Alameda
2,01/03/2020,1.8,ppb,1,Oakland West,Alameda
3,01/04/2020,1.4,ppb,1,Oakland West,Alameda
4,01/05/2020,0.7,ppb,0,Oakland West,Alameda

In [50]:
#Check Count for SF & Oakland West
SO2_2020.count()

Date                                  2368
Daily_Max_1-hour_SO2_Concentration    2368
UNITS                                 2368
DAILY_AQI_VALUE                       2368
Site_Name                             2368
COUNTY                                2368
dtype: int64

In [51]:
#To CSV
SO2_2020.to_csv(r'SO2_2020_clean.csv', header= True, index=False)

In [52]:
##Load CSV for PM2.5
file_to_load = ("SF 2020 PM10.csv")
PM10_2020 =pd.read_csv(file_to_load)
PM10_2020.head()

,Date,Source,Site ID,POC,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/04/2020,AQS,60130002,1,10,ug/m3 SC,9,Concord,1,100.0,81102,PM10 Total 0-10um STP,41860,"San Francisco-Oakland-Hayward, CA",6,California,13,Contra Costa,37.936013,-122.026154
1,01/16/2020,AQS,60130002,1,3,ug/m3 SC,3,Concord,1,100.0,81102,PM10 Total 0-10um STP,41860,"San Francisco-Oakland-Hayward, CA",6,California,13,Contra Costa,37.936013,-122.026154
2,01/28/2020,AQS,60130002,1,9,ug/m3 SC,8,Concord,1,100.0,81102,PM10 Total 0-10um STP,41860,"San Francisco-Oakland-Hayward, CA",6,California,13,Contra Costa,37.936013,-122.026154
3,02/09/2020,AQS,60130002,1,7,ug/m3 SC,6,Concord,1,100.0,81102,PM10 Total 0-10um STP,41860,"San Francisco-Oakland-Hayward, CA",6,California,13,Contra Costa,37.936013,-122.026154
4,02/21/2020,AQS,60130002,1,17,ug/m3 SC,16,Concord,1,100.0,81102,PM10 Total 0-10um STP,41860,"San Francisco-Oakland-Hayward, CA",6,California,13,Contra Costa,37.936013,-122.026154

In [53]:
#Check Columns
PM10_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean PM10 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [54]:
#Check Null Values
PM10_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [55]:
#Drop Columns
PM10_2020 = PM10_2020.drop(columns=['Source','Site ID','POC','AQS_PARAMETER_CODE','DAILY_OBS_COUNT','PERCENT_COMPLETE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'SITE_LATITUDE', 'SITE_LONGITUDE'], axis=1)

In [56]:
#Check DataFrame 
PM10_2020.head()

,Date,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,COUNTY
0,01/04/2020,10,ug/m3 SC,9,Concord,Contra Costa
1,01/16/2020,3,ug/m3 SC,3,Concord,Contra Costa
2,01/28/2020,9,ug/m3 SC,8,Concord,Contra Costa
3,02/09/2020,7,ug/m3 SC,6,Concord,Contra Costa
4,02/21/2020,17,ug/m3 SC,16,Concord,Contra Costa

In [57]:
#Rename Site Name & Concentration Columns
PM10_2020 = PM10_2020.rename(columns={"Site Name": "Site_Name"})
PM10_2020 = PM10_2020.rename(columns={"Daily Mean PM10 Concentration": "Daily_Mean_PM10_Concentration"})
PM10_2020.head()

,Date,Daily_Mean_PM10_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
0,01/04/2020,10,ug/m3 SC,9,Concord,Contra Costa
1,01/16/2020,3,ug/m3 SC,3,Concord,Contra Costa
2,01/28/2020,9,ug/m3 SC,8,Concord,Contra Costa
3,02/09/2020,7,ug/m3 SC,6,Concord,Contra Costa
4,02/21/2020,17,ug/m3 SC,16,Concord,Contra Costa

In [58]:
#Filter for SF & Oakland West
PM10_2020 = PM10_2020[(PM10_2020.Site_Name == "Oakland West") | (PM10_2020.Site_Name == "San Francisco")]
PM10_2020.head(10)

,Date,Daily_Mean_PM10_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name,COUNTY
213,01/04/2020,14,ug/m3 SC,13,San Francisco,San Francisco
214,01/16/2020,9,ug/m3 SC,8,San Francisco,San Francisco
215,01/28/2020,20,ug/m3 SC,19,San Francisco,San Francisco
216,02/09/2020,17,ug/m3 SC,16,San Francisco,San Francisco
217,02/21/2020,29,ug/m3 SC,27,San Francisco,San Francisco
218,03/04/2020,30,ug/m3 SC,28,San Francisco,San Francisco
219,03/16/2020,4,ug/m3 SC,4,San Francisco,San Francisco
220,03/28/2020,15,ug/m3 SC,14,San Francisco,San Francisco
221,04/09/2020,8,ug/m3 SC,7,San Francisco,San Francisco
222,04/21/2020,22,ug/m3 SC,20,San Francisco,San Francisco

In [59]:
#Check Count SF & Oakland West
PM10_2020.count()

Date                             31
Daily_Mean_PM10_Concentration    31
UNITS                            31
DAILY_AQI_VALUE                  31
Site_Name                        31
COUNTY                           31
dtype: int64

In [60]:
#To CSV
PM10_2020.to_csv(r'PM10_2020_clean.csv', header= True, index=False)