In [1]:
#Importing packages
import pandas as pd
import os
import numpy as np
import glob

In [2]:
#path = "/home/user/data/"
path = "/Users/selenajdeleon/Desktop/Analysis_Projects/Final_Project/ML---Final-Project---Pollution-Future-Impact-Analysis-/clean_data"

#Selecting all PM2.5 CSV files
all_files = glob.glob(os.path.join(path, "20**_pm2_5.csv"))

#Sorting files by 'Date' column (asc)
all_files.sort()

#Merging 2015-2020 PM2.5 files
df_from_each_file = [pd.read_csv(f, sep=',') for f in all_files]
df_from_each_file
df_merged   = pd.concat(df_from_each_file)

#Creating CSV file for merged PM2.5 files (2015-2020)
df_merged.to_csv("pm2_5.csv", header = True, index = False)

In [3]:
df_merged.head()

,Date,Daily_Mean_PM2.5_Concentration,UNITS,DAILY_AQI_VALUE,Site_Name
0,01/01/2015,13.9,ug/m3 LC,55,San Francisco
1,01/02/2015,22.6,ug/m3 LC,73,San Francisco
2,01/03/2015,27.9,ug/m3 LC,84,San Francisco
3,01/04/2015,28.8,ug/m3 LC,86,San Francisco
4,01/05/2015,20.6,ug/m3 LC,69,San Francisco

In [4]:
#Renaming DAILY_AQI_VALUE column to include name of pollutant for ML model
df_merged = df_merged.rename(columns={"DAILY_AQI_VALUE": "AQI_PM_2_5"})
df_merged.head()

,Date,Daily_Mean_PM2.5_Concentration,UNITS,AQI_PM_2_5,Site_Name
0,01/01/2015,13.9,ug/m3 LC,55,San Francisco
1,01/02/2015,22.6,ug/m3 LC,73,San Francisco
2,01/03/2015,27.9,ug/m3 LC,84,San Francisco
3,01/04/2015,28.8,ug/m3 LC,86,San Francisco
4,01/05/2015,20.6,ug/m3 LC,69,San Francisco

In [5]:
#Creating pm_2_5.csv to reflect changes for ML model; (delete pm2_5.csv)
df_merged.to_csv("pm_2_5.csv", header = True, index = False)